POST http://localhost:7071/api/agent_httptrigger HTTP/1.1

{
  "message": "what is the northwind plan?",
  "agentid": "asst_Aqvo3QPJreGvUsqqRZ1BLGPe",
  "threadid": "thread_yafFVou6cl2sKSRKKtcg0TBj"
}


###

POST https://fapp-agent-f4t.azurewebsites.net/api/agent_httptrigger HTTP/1.1

{
  "message": "what is my hire date?",
  "agentid": "asst_Aqvo3QPJreGvUsqqRZ1BLGPe"
}


###

POST http://localhost:7071/api/agent_httptrigger HTTP/1.1

{
  "message": "Hello, can you help me?",
  "agent_name": "HRAssistantExplicitMessages102",
  "instructions": "You are a friendly support assistant."
}


###

POST http://localhost:7071/api/agent_httptrigger HTTP/1.1

{
  "message": "what are northwind plans?",
  "agent_name": "Agent-001",
  "instructions": "You are an AI assistant that answer questions about HR benefits and health plan details. End your answer witha fun fact."
}


###

POST http://localhost:7071/api/agent_httptrigger HTTP/1.1

{
  "message": "what are northwind plans?",
  "instructions": "You are an AI assistant that answer questions about HR benefits and health plan details. End your answer with a fun fact."
}


###

POST http://localhost:7071/api/agent_httptrigger HTTP/1.1

{
  "message": "who is my manager",
  "agent_name": "NewAgent007",
  "parameters": {
    "user_id": "SHSU",
    "user_full_name": "HSU, Susan"
  }
}


###

POST http://localhost:7071/api/agent_httptrigger HTTP/1.1

{
  "message": "who is my manager",
  "agent_name": "NewAgent008",
  "parameters": {
    "user_id": "SCHOY",
    "user_full_name": "CHOY, Steven"
  },
  "threadid": "conv_688bdadc0a6b7de600jqxpMEXv2QY6NELvAutatlPUUOBqehPw"
}


